name: Generate changelog
on:
  release:
    types: [created, edited]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: faberNovel/github-changelog-generator-action@v1.0.0-alpha02
      with:
        options: --token ${{ secrets.GITHUB_TOKEN }}
