name: Generate changelog
on:
  release:
    types: [created, edited]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: fabernovel/github-changelog-generator-action@{latest-release}
      with:
        options: --token ${{ secrets.GITHUB_TOKEN }}
